language: objective-c
osx_image: xcode10
xcode_project: DiveLane.xcworkspace # path to your xcodeproj folder
xcode_scheme: DiveLane
xcode_destination: platform=iOS Simulator, OS=12.0, name=iPhone X
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -scheme DiveLane -workspace DiveLane.xcworkspace -sdk iphonesimulator build test
after_success:
 notifications:
  email:
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change] - bash <(curl -s https://codecov.io/bash)
